# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Eclipse Products

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
    tags: "v**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.5

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -U -B package --file pom.xml

    - name: Save Eclipse Distribution (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Distribution Windows"
        path: "releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-win32*.zip"
    
    - name: Save Eclipse Distribution (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Distribution Linux"
        path: "releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux*.zip"

    - name: Save Eclipse Distribution (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Distribution MacOS"
        path: "releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx*.zip"
  
    - name: Move Distributions
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir dist 
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-win32*.zip dist/Artemis_Windows.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux*.zip dist/Artemis_Linux.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx*.zip dist/Artemis_MacOS.zip
          
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          dist/Artemis_Windows.zip
          dist/Artemis_Linux.zip
          dist/Artemis_MacOS.zip
      
