# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update Site

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2.1.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -U -B package --file pom.xml
        
    - name: Upload UpdateSite
      uses: actions/upload-artifact@v2
      with:
        name: updatesite
        path: releng/edu.kit.kastel.sdq.eclipse.grading.updatesite/target/repository/
  
    - name: Checkout GH Pages
      uses: actions/checkout@v2.3.1
      with:
        ref: gh-pages

    - run: rm -rf updatesite/

    - name: Download UpdateSite
      uses: actions/download-artifact@v2
      with:
        name: updatesite
        path: updatesite/
        
    - run: echo "You will find the update site at: https://kit-sdq.github.io/programming-lecture-eclipse-artemis-grading/updatesite/" > index.html

    - name: Commit
      uses: zwaldowski/git-commit-action@v1

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}

